# Generated by Django 5.1.1 on 2024-10-28 06:07

from django.db import migrations

def set_default_about(apps, schema_editor):
    Employee = apps.get_model('api', 'Employee')
    # Set a default value for the 'about' field if it's currently null
    Employee.objects.filter(about__isnull=True).update(about='No information provided.')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employee_about'),  # Make sure this points to the last migration
    ]

    operations = [
        migrations.RunPython(set_default_about),
    ]
