# Generated by Django 5.1.1 on 2024-10-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_employee_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
